#!/bin/bash

script_path="$(realpath ${0})"
# echo "script_path: ${script_path}"

script_dir="$(dirname ${script_path})"
# echo "script_dir: ${script_dir}"

export CLASSPATH="${script_dir}/bin"
# echo "CLASSPATH: ${CLASSPATH}"

arguments=${@}

if [ -z "${arguments}" ]
then
    # Displays usage of jrep
    echo "Usage: jrep [PATTERN]"
    exit 1
fi

if [ "${arguments}" = "--help" ]
then
    # Displays usage of jrep
    echo "Usage: jrep [PATTERN]"
    exit 1
fi

if [ ! "${arguments}" = "--help" ]
then
    # Runs Java program
    java comp290.Jrep "${arguments}"
    exit 0
fi

